Shorten parameter lists by containing StorageEngine, TransactionIdStore, and LogFiles into new CoreBuildStore class
nickplucker/neo4j pull request #2
Opened 2018-12-13 09:05 UTC by rabex028

This request addresses issue #1.

The purpose of the changes in this request is to mitigate a code design flaw, or *smell*, known as long parameter lists in the `NeoStoreDataSource` class. Long parameter lists occur when an excessive number of arguments are passed into a class or method, which can result in code that is both harder to read and maintain. 

We are focusing on `NeoStoreDataSource.java` for this refactoring because it was identified by an online tool called codescene as being a refactoring target. Codescene determined that the code in this class is relatively complicated, and also that changes are frequently made to it. Because of these two factors, a significant amount of development time and effort likely goes into working on `NeoStoreDataSource.java`. Refactoring this class to make it easier to understand can therefore reduce the amount of development resources that are spent on this code over the long run.

The long parameter list smell is being addressed because an IDE tool designed to search for code smells, named Sonar Lint, flagged several cases of it. Sonar Lint recommends that a maximum of 7 parameters are given to methods or classes, and there are multiple parameter lists which exceed this amount in `NeoStoreDataSource.java`.

Our general approach to address this smell has been to find groups of parameters that are common within multiple parameter lists, enclose them within a new class, and pass this class in as a parameter instead.

* Commit 74106c8 creates a new class we have named `CoreBuildStore` to contain the parameters `StorageEngine`, `TransactionIdStore`, and `LogFiles`. These three parameters are then removed from the list given to the method `buildRecovery()` and are replaced with `CoreBuildStore`.

* Commit d9e1d33 performs a similar refactoring by replacing `StorageEngine`, `TransactionIdStore`, and `LogFiles` again with `CoreBuildStore` in the `buildKernel()` and `buildTransactionLogs()` methods' parameter lists. In addition, unnecessary redundant variable assignments and deprecated method calls were removed as recommended by Sonar Lint.

2018-12-13 21:02 UTC, YujingSong approved these changes
It is a good idea to create a new class in your case.  Looks like did some reorganization in the original main class, and combined some functions together.  Very good job.

2018-12-13 21:36 UTC, schon094 approved these changes
Creating a new class to contain common objects is a good way to reduce the amount of parameters passed to these methods.
Nice job cleaning up unnecessary variables as well.

2018-12-13 21:56 UTC, CMenne requested changes
While we feel that the changes you made reduced the number of parameters in certain methods and thus improved readability, we feel that this wasn't a beneficial change due to the fact that message chains were introduced into other areas. On it's own these changes are not sufficiently beneficial to warrant accepting the pull request. If logic was integrated into CoreBuildStore, this would remedy the situation. 

@Xaivteev @CMenne @twarling

2018-12-13 21:56 UTC, CMenne commented on community/kernel/src/main/java/org/neo4j/kernel/CoreBuildStore.java
> +public class CoreBuildStore {
In it's current iteration, this class is a 'data class'. Potentially in the future, logic could be migrated into the class and if not, it might be more valuable to revert these changes.

2018-12-13 21:56 UTC, CMenne commented on community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java
> +        storageEngine = null;
:+1:

2018-12-13 21:56 UTC, CMenne commented on community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java
> +                new LogPruningImpl( fs, coreBuildStore.getLogFiles(), logProvider, new LogPruneStrategyFactory(), clock, config );
While you reduced message chaining in other parts of the code, you've added it to numerous other parts of the code.

2018-12-13 21:56 UTC, CMenne commented on community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java
> +    private NeoStoreTransactionLogModule buildTransactionLogs( CoreBuildStore coreBuildStore, Config config,
By reducing the number of parameters, the code is easier to read.

2018-12-13 21:58 UTC, bemica approved these changes
I agree that CoreBuildStore is a data class, and it would be nice to see some functionality in it (which would also help to reduce message chains) but this is still a good improvement over the previous build, and is a good stepping stone for further refactoring

2018-12-14 01:17 UTC, stev0531 approved these changes
I also agree that `CoreBuildStore` is a data class right now, but as was also already mentioned, it's a good stepping stone to refactor further. The pull request message, though, was really well done. You explain why you chose the smell you did, how you planned to address it, the tools you used to find it, and even what the tools were. I found this really nice because if I didn't have any previous knowledge about the tools or what you planned to do, I still would have a good understanding of your reasoning for why your changes matter.

2018-12-16 07:47 UTC, globbycodes approved these changes
I think overall you have done a good job. The list of parameters as mentioned actually got reduced and therefore made the code a bit easier to understand. The documentation of the pull request is good. I could understand the big picture of what was the problem.

2018-12-16 07:47 UTC, GLOBBIMUS commented on community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java
> +            CoreBuildStore coreBuildStore = new CoreBuildStore();
I think this is a nice idea of reducing the list of parameters by creating `CoreBuildStore` puttin everything into that class.
I don't know what `logFiles`. `storageEngine` and `transactionIdStore` really are. But I'm assuming that these are related and it makes sense to put them together.

2018-12-16 07:47 UTC, GLOBBIMUS commented on community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java
> +                new LogPruningImpl( fs, coreBuildStore.getLogFiles(), logProvider, new LogPruneStrategyFactory(), clock, config );
As an option you could have done something like that:
```Java
LogFiles logFiles = coreBuildStore.getLogFiles()
```
and then use that instead of calling  `coreBuildStore.getLogFiles()` every time.

2018-12-20 04:14 UTC, pluck011 commented
@CMenne Would you be able to review our PR again? We implemented some changes that you requested.

2018-12-20 04:58 UTC, CMenne approved these changes
After further review, this does seem like an improvement. I agree, this does reduce the total number of parameters in these methods.

2018-12-20 04:58 UTC, CMenne commented on community/kernel/src/main/java/org/neo4j/kernel/NeoStoreDataSource.java
> +                new LogPruningImpl( fs, coreBuildStore.getLogFiles(), logProvider, new LogPruneStrategyFactory(), clock, config );
👍

2018-12-21 16:46 UTC, merged